// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyFile(arg1) {
  return window['go']['usecase']['Usecase']['CopyFile'](arg1);
}

export function CreateDirectory(arg1) {
  return window['go']['usecase']['Usecase']['CreateDirectory'](arg1);
}

export function GetConfig() {
  return window['go']['usecase']['Usecase']['GetConfig']();
}

export function GetNodeTree() {
  return window['go']['usecase']['Usecase']['GetNodeTree']();
}

export function MoveToTrash(arg1) {
  return window['go']['usecase']['Usecase']['MoveToTrash'](arg1);
}

export function OpenOrCreateFile(arg1) {
  return window['go']['usecase']['Usecase']['OpenOrCreateFile'](arg1);
}

export function RenamePath(arg1) {
  return window['go']['usecase']['Usecase']['RenamePath'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['usecase']['Usecase']['SaveFile'](arg1);
}

export function SearchInFiles(arg1) {
  return window['go']['usecase']['Usecase']['SearchInFiles'](arg1);
}

export function SetRootPath(arg1) {
  return window['go']['usecase']['Usecase']['SetRootPath'](arg1);
}

export function WriteLog(arg1) {
  return window['go']['usecase']['Usecase']['WriteLog'](arg1);
}
