// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {lib} from '../models';
import {model} from '../models';

export function CreateDirectory(arg1:dto.CreateDirectoryReq):Promise<void>;

export function GetConfig():Promise<lib.Config>;

export function GetNodeTree():Promise<model.Node>;

export function MoveToTrash(arg1:dto.MoveToTrashReq):Promise<void>;

export function OpenOrCreateFile(arg1:dto.OpenOrCreateFileReq):Promise<string>;

export function RenamePath(arg1:dto.RenamePathReq):Promise<void>;

export function SaveFile(arg1:dto.SaveFileReq):Promise<void>;

export function SearchInFiles(arg1:dto.SearchInFilesReq):Promise<Array<model.Match>>;

export function SetRootPath(arg1:dto.SetRootPathReq):Promise<void>;

export function WriteLog(arg1:dto.WriteLogReq):Promise<void>;
