// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDirectory(arg1) {
  return window['go']['usecase']['Usecase']['CreateDirectory'](arg1);
}

export function GetConfig() {
  return window['go']['usecase']['Usecase']['GetConfig']();
}

export function GetNodeTree() {
  return window['go']['usecase']['Usecase']['GetNodeTree']();
}

export function OpenOrCreateFile(arg1) {
  return window['go']['usecase']['Usecase']['OpenOrCreateFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['usecase']['Usecase']['SaveFile'](arg1, arg2);
}

export function SetRootPath(arg1) {
  return window['go']['usecase']['Usecase']['SetRootPath'](arg1);
}

export function WriteLog(arg1, arg2) {
  return window['go']['usecase']['Usecase']['WriteLog'](arg1, arg2);
}
