// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetRootPath(arg1:string):Promise<void>;

export function WriteLog(arg1:string):Promise<void>;
