// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetNodeTree():Promise<model.Node>;

export function OpenFile(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SetRootPath(arg1:string):Promise<void>;

export function WriteLog(arg1:any):Promise<void>;
